# Generated by Django 3.0.5 on 2020-04-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('BM_Num', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Food_Name', models.TextField(max_length=20)),
                ('User_ID', models.TextField(max_length=15)),
                ('Food_Num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Num', models.IntegerField(primary_key=True, serialize=False)),
                ('Food_Name', models.TextField(max_length=15)),
                ('Category', models.TextField(max_length=5)),
                ('Serving_Size', models.FloatField(default=0)),
                ('Kcal', models.FloatField(default=0)),
                ('Carbo', models.FloatField(default=0)),
                ('Protein', models.FloatField(default=0)),
                ('Fat', models.FloatField(default=0)),
                ('Saccharide', models.FloatField(default=0)),
                ('Natrium', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('Stats_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('Carbo', models.FloatField(default=0)),
                ('Protein', models.FloatField(default=0)),
                ('Fat', models.FloatField(default=0)),
                ('Saccharide', models.FloatField(default=0)),
                ('Natrium', models.FloatField(default=0)),
                ('User_ID', models.IntegerField(default=0)),
                ('Food_Food_Num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('PW', models.TextField(max_length=15)),
                ('User_Name', models.TextField(max_length=5)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(max_length=1)),
                ('Height', models.FloatField(default=0)),
                ('Weight', models.FloatField(default=0)),
                ('Activity_Index', models.IntegerField(default=0)),
                ('User_Kcal', models.FloatField(default=0)),
            ],
        ),
    ]
