# Generated by Django 3.0.5 on 2020-04-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Num', models.IntegerField(primary_key=True, serialize=False)),
                ('FoodName', models.TextField(max_length=15)),
                ('Category', models.TextField(max_length=5)),
                ('ServingSize', models.FloatField(default=0)),
                ('Kcal', models.FloatField(default=0)),
                ('Carbo', models.FloatField(default=0)),
                ('Protein', models.FloatField(default=0)),
                ('Fat', models.FloatField(default=0)),
                ('Saccharide', models.FloatField(default=0)),
                ('Natrium', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('PW', models.TextField(max_length=15)),
                ('UserName', models.TextField(max_length=5)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(max_length=1)),
                ('Height', models.FloatField(default=0)),
                ('Weight', models.FloatField(default=0)),
                ('Activity_Index', models.IntegerField(default=0)),
                ('UserKcal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('StatsID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('Carbo', models.FloatField(default=0)),
                ('Protein', models.FloatField(default=0)),
                ('Fat', models.FloatField(default=0)),
                ('Saccharide', models.FloatField(default=0)),
                ('Natrium', models.FloatField(default=0)),
                ('FoodFoodNum', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.User')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('BMNum', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.TextField(max_length=20)),
                ('FoodNum', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.User')),
            ],
        ),
    ]
